# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "debian/bookworm64"

  config.vm.define "mflores" do |control|
    control.vm.hostname = "mfloresS"
    control.vm.network "private_network", ip: "192.168.56.110", hostname: true
    control.vm.provider "virtualbox" do |v|
      v.memory = "1024"
      v.cpus = 2
    end
    # Copy files from the host machine to the VM
    control.vm.provision "file", source: "./scripts/srcs/deploy-app1.yaml", destination: "/home/vagrant/deploy-app1.yaml"
    control.vm.provision "file", source: "./scripts/srcs/service-app1.yaml", destination: "/home/vagrant/service-app1.yaml"
    control.vm.provision "file", source: "./scripts/srcs/deploy-app2.yaml", destination: "/home/vagrant/deploy-app2.yaml"
    control.vm.provision "file", source: "./scripts/srcs/service-app2.yaml", destination: "/home/vagrant/service-app2.yaml"
    control.vm.provision "file", source: "./scripts/srcs/deploy-app3.yaml", destination: "/home/vagrant/deploy-app3.yaml"
    control.vm.provision "file", source: "./scripts/srcs/service-app3.yaml", destination: "/home/vagrant/service-app3.yaml"
    control.vm.provision "file", source: "./scripts/srcs/ingress.yaml", destination: "/home/vagrant/ingress.yaml"
    control.vm.provision "shell", path: './scripts/server.sh'
  end
  
end
